import UIKit

struct StringConstants {
    static let k: String = ""
    static let kLblShop: String = "Shop"
    static let kLblEmail: String = "email"
    static let kMsgForgetPassword: String = "Forget Password ?"
    static let kLblOrSignUpWith: String = "Or sign up with"
    static let kMsgConfirmPasswor: String = "Confirm Password"
    static let kLblBlender: String = "Blender"
    static let kLblPhone: String = "Phone"
    static let kMsgAlreadyHaveAn: String = "Already have an account ? Sign In"
    static let kLblDescription: String = "Description"
    static let kLblLoginAccount: String = "Login Account"
    static let kLblLogin: String = "Login"
    static let kLblPost: String = "Post"
    static let kLblIgnition: String = "Ignition"
    static let kLblLearnMore: String = "Learn More"
    static let kLblExploreTheApp: String = "Explore the app"
    static let kMsgAlreadyHaveAn2: String = "Already have an account ? "
    static let kLblUniShop: String = "Uni Shop"
    static let kLblUni: String = "Uni "
    static let kMsgNotRegisterYe: String = "Not register yet ? Create Account"
    static let kLblCreateAccount: String = "Create Account"
    static let kMsgWelcomeToUnis: String = "Welcome to Unishop"
    static let kMsgInstitutionalE: String = "Institutional Email"
    static let kLblCharcoal: String = "Charcoal"
    static let kHttpFail: String = "HTTP request failed"
    static let kLblSignIn: String = "Sign In"
    static let kMsgWeReSoHappy: String =
        "We’re so happy that you want to join us, now we need to validate your data and check if you’re elegible, so we will need the following data"
    static let kLblAdd: String = "Add"
    static let kMsgNotRegisterYe2: String = "Not register yet ? "
    static let kLblLetsStart: String = "Lets Start"
    static let kUnableToFetch: String = "Unable to fetch data"
    static let kLblLogin2: String = "Login "
    static let kLblMellisaCarter: String = "Mellisa Carter"
    static let kMsgYouReAtUnian: String = "You’re at Uniandes Workspace !"
    static let kLblAnihilation: String = "Anihilation"
    static let kLblSignUp: String = "Sign Up"
    static let kLblPassword: String = "Password"
    static let kLblTitle: String = "Name"
    static let kMsgLoremIpsumDol: String =
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi maecenas quis interdum enim enim molestie faucibus. Pretium non non massa eros, nunc, urna. Ac laoreet sagittis donec vel. Amet, duis justo, quam quisque egestas. Quam enim at dictum condimentum. Suspendisse."
    static let kLblName: String = "Name"
    static let kMsgIAcceptThePr: String =
        "I accept the privacy policy and data consent of the data, I understand I have read it and understand it.\nWe’re not under “Universidad de los Andes” rights."
    static let kLblOil: String = "Oil"
    static let kLblUsername: String = "Username"
    static let kInvalidUrl: String = "Invalid URL"
    static let kLblMail: String = "Mail"
    static let kLblTalesOfOld: String = "Tales of old"
    static let kLblNewPost: String = "New Post"
    static let kLblNewProduct: String = "Is a new product?"
    static let kLblPrice: String = "Price"
    static let kLblSubject: String = "Subject"
    static let kLblDegree: String = "Degree"
}
